"""init

Revision ID: 158442264d3f
Revises: 
Create Date: 2025-05-27 14:54:11.659241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158442264d3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('csv_filename', sa.String(), nullable=False),
    sa.Column('dependent_variable', sa.String(), nullable=False),
    sa.Column('independent_variables', sa.JSON(), nullable=False),
    sa.Column('formula', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_requests_id'), 'analysis_requests', ['id'], unique=False)
    op.create_table('regression_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('coefficients_json', sa.JSON(), nullable=False),
    sa.Column('std_errors_json', sa.JSON(), nullable=False),
    sa.Column('t_statistics_json', sa.JSON(), nullable=False),
    sa.Column('p_values_json', sa.JSON(), nullable=False),
    sa.Column('r_squared', sa.Float(), nullable=False),
    sa.Column('adj_r_squared', sa.Float(), nullable=False),
    sa.Column('f_statistic', sa.Float(), nullable=False),
    sa.Column('f_p_value', sa.Float(), nullable=False),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('confidence_intervals', sa.JSON(), nullable=False),
    sa.Column('formula', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regression_results')
    op.drop_index(op.f('ix_analysis_requests_id'), table_name='analysis_requests')
    op.drop_table('analysis_requests')
    # ### end Alembic commands ###
