"""changed

Revision ID: 40c0d018213f
Revises: 478db6f951de
Create Date: 2025-05-27 10:57:44.936842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c0d018213f'
down_revision: Union[str, None] = '478db6f951de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regression_results', sa.Column('confidence_intervals', sa.JSON(), nullable=False))
    op.add_column('regression_results', sa.Column('formula', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regression_results', 'formula')
    op.drop_column('regression_results', 'confidence_intervals')
    # ### end Alembic commands ###
